// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4-R8CBBiXuR-TKj_xYN-__W0GGHl_4JM',
    appId: '1:5127295795:web:a6a31df015c938143a6446',
    messagingSenderId: '5127295795',
    projectId: 'crud-bceb8',
    authDomain: 'crud-bceb8.firebaseapp.com',
    storageBucket: 'crud-bceb8.appspot.com',
    measurementId: 'G-2EN1CGL3C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpFsYtQY8hIiamSviPKJbdJJbWySt-a0k',
    appId: '1:5127295795:android:d4e9336d8fc8db513a6446',
    messagingSenderId: '5127295795',
    projectId: 'crud-bceb8',
    storageBucket: 'crud-bceb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJkye-3Tv_h2chm37SXuHsY6mgueUTH2c',
    appId: '1:5127295795:ios:d597486185ebb2693a6446',
    messagingSenderId: '5127295795',
    projectId: 'crud-bceb8',
    storageBucket: 'crud-bceb8.appspot.com',
    iosBundleId: 'com.codigocorrecto.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJkye-3Tv_h2chm37SXuHsY6mgueUTH2c',
    appId: '1:5127295795:ios:d597486185ebb2693a6446',
    messagingSenderId: '5127295795',
    projectId: 'crud-bceb8',
    storageBucket: 'crud-bceb8.appspot.com',
    iosBundleId: 'com.codigocorrecto.crud',
  );
}
